version : "3.8"

services:
  base:
    container_name: django_app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - psql-db
    
  psql-db:
    container_name: postgresql_database
    image: postgres
    env_file: .env
    ports:
      - 5432:5432

