# Generated by Django 3.1 on 2021-02-06 21:38

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='user json')),
                ('track_time', models.DateTimeField(default=datetime.datetime(2021, 2, 6, 21, 38, 59, 165245, tzinfo=utc), verbose_name='time saved data')),
            ],
            options={
                'verbose_name': 'Track User',
                'verbose_name_plural': 'Track Users',
            },
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.BigIntegerField(unique=True, verbose_name='id')),
                ('id_str', models.CharField(max_length=20, unique=True, verbose_name='id_str')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('screen_name', models.CharField(max_length=200, verbose_name='screen_name')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.SlugField(blank=True, max_length=500, null=True, verbose_name='url')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='description')),
                ('protected', models.BooleanField(verbose_name='protected')),
                ('verified', models.BooleanField(verbose_name='verified')),
                ('followers_count', models.IntegerField(verbose_name='followers_count')),
                ('friends_count', models.IntegerField(verbose_name='friends_count')),
                ('listed_count', models.IntegerField(verbose_name='listed_count')),
                ('favourites_count', models.IntegerField(verbose_name='favourites_count')),
                ('statuses_count', models.IntegerField(verbose_name='statuses_count')),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
                ('profile_banner_url', models.SlugField(blank=True, max_length=500, null=True, verbose_name='profile_banner_url')),
                ('profile_image_url_https', models.SlugField(blank=True, max_length=500, null=True, verbose_name='profile_image_url_https')),
            ],
            options={
                'verbose_name': 'Twitter User',
                'verbose_name_plural': 'Twitter Users',
            },
        ),
        migrations.CreateModel(
            name='TwitterStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
                ('tweet_id', models.BigIntegerField(verbose_name='id')),
                ('id_str', models.CharField(max_length=20, verbose_name='id_str')),
                ('text', models.CharField(max_length=1000, verbose_name='text')),
                ('source', models.CharField(max_length=100)),
                ('truncated', models.BooleanField(verbose_name='truncated')),
                ('in_reply_to_status_id', models.BigIntegerField(blank=True, null=True, verbose_name='in_reply_to_status_id')),
                ('in_reply_to_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='in_reply_to_user_id')),
                ('in_reply_to_screen_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='in_reply_to_screen_name')),
                ('id_quoted_status', models.BigIntegerField(blank=True, null=True, verbose_name='quoted_status_id')),
                ('is_quote_status', models.BooleanField(verbose_name='is_quote_status')),
                ('quote_count', models.IntegerField(blank=True, null=True, verbose_name='quote_count')),
                ('reply_count', models.IntegerField(blank=True, null=True, verbose_name='reply_count')),
                ('retweet_count', models.IntegerField(blank=True, null=True, verbose_name='retweet_count')),
                ('favorite_count', models.IntegerField(blank=True, null=True, verbose_name='favorite_count')),
                ('lang', models.CharField(blank=True, max_length=30, null=True, verbose_name='language')),
                ('entities', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='entities')),
                ('quoted_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoted', to='data.twitterstatus', verbose_name='quoted_status')),
                ('retweeted_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweeted', to='data.twitterstatus', verbose_name='retweeted_status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.twitteruser', verbose_name='user')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
    ]
